#!/usr/bin/env python3
"""Synchronize a directory with Google Drive via gog CLI."""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import html
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone

CONFIG_NAME = "gd-sync.yml"
DEFAULT_IGNORES = [CONFIG_NAME, ".agents/", ".codex/", ".claude/"]
FOLDER_MIME = "application/vnd.google-apps.folder"
GOOGLE_NATIVE_PREFIX = "application/vnd.google-apps."
GOOGLE_EXPORTS = {
    "application/vnd.google-apps.document": ("docx", ".docx"),
    "application/vnd.google-apps.spreadsheet": ("xlsx", ".xlsx"),
    "application/vnd.google-apps.presentation": ("pptx", ".pptx"),
    "application/vnd.google-apps.drawing": ("png", ".png"),
}
GOOGLE_NATIVE_MODES = {"html", "pointer", "export"}
GOOGLE_NATIVE_ALIASES = {"link": "html"}


def configure_stdio() -> None:
    """Keep status output safe for Windows consoles with a non-UTF-8 default."""
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8", errors="replace")
LINK_SUFFIX = ".gdrive.html"
GENERATED_LINK_MARKER = '<meta name="generator" content="gd-sync">'
POINTER_EXTENSIONS = {
    "application/vnd.google-apps.document": ".gdoc",
    "application/vnd.google-apps.spreadsheet": ".gsheet",
    "application/vnd.google-apps.presentation": ".gslides",
    "application/vnd.google-apps.drawing": ".gdraw",
    "application/vnd.google-apps.form": ".gform",
    "application/vnd.google-apps.map": ".gmap",
    "application/vnd.google-apps.site": ".gsite",
    "application/vnd.google-apps.script": ".gscript",
}
POINTER_WARNING = "WARNING! DO NOT EDIT THIS FILE! ANY CHANGES MADE WILL BE LOST!"


def find_gog() -> str | None:
    found = shutil.which("gog")
    if found:
        return found
    if os.name == "nt":
        fallback = Path.home() / ".local" / "bin" / "gog.exe"
        if fallback.is_file():
            return str(fallback)
    return None


def strip_inline_comment(value: str) -> str:
    quote = ""
    escaped = False
    for index, character in enumerate(value):
        if escaped:
            escaped = False
            continue
        if character == "\\" and quote == '"':
            escaped = True
            continue
        if character in {'"', "'"}:
            if not quote:
                quote = character
            elif quote == character:
                quote = ""
            continue
        if character == "#" and not quote and (index == 0 or value[index - 1].isspace()):
            return value[:index].rstrip()
    return value.strip()


def unquote(value: str) -> str:
    value = strip_inline_comment(value).strip()
    if value in {"", "null", "~"}:
        return ""
    if value.startswith('"') and value.endswith('"'):
        return str(json.loads(value))
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1].replace("''", "'")
    return value


def normalize_google_native(value: object) -> str:
    mode = str(value or "html").strip().lower()
    mode = GOOGLE_NATIVE_ALIASES.get(mode, mode)
    if mode not in GOOGLE_NATIVE_MODES:
        raise ValueError("google_native must be 'html', 'pointer', or 'export'")
    return mode


def load_config(path: Path) -> dict[str, object]:
    result: dict[str, object] = {
        "drive_folder_id": "",
        "google_native": "html",
        "last_sync_at": "",
        "ignore": [],
    }
    section = ""
    for number, raw in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("-"):
            if section != "ignore":
                raise ValueError(f"line {number}: list item is only valid under ignore")
            items = result["ignore"]
            assert isinstance(items, list)
            items.append(unquote(line[1:].strip()))
            continue
        if ":" not in line:
            raise ValueError(f"line {number}: expected key: value")
        key, value = line.split(":", 1)
        key = key.strip()
        if key not in result:
            raise ValueError(f"line {number}: unknown key {key!r}")
        if key == "ignore":
            if strip_inline_comment(value).strip() not in {"", "[]"}:
                raise ValueError(f"line {number}: ignore must be a YAML list")
            section = "ignore"
        else:
            result[key] = unquote(value)
            section = ""
    result["google_native"] = normalize_google_native(result["google_native"])
    ignores = [str(item) for item in result["ignore"] if str(item).strip()]
    result["ignore"] = list(dict.fromkeys(DEFAULT_IGNORES + ignores))
    return result


def write_config(path: Path, config: dict[str, object]) -> None:
    folder_id = str(config.get("drive_folder_id") or "")
    mode = normalize_google_native(config.get("google_native"))
    last_sync = str(config.get("last_sync_at") or "")
    ignores = [str(item) for item in config.get("ignore", DEFAULT_IGNORES)]
    ignores = list(dict.fromkeys(DEFAULT_IGNORES + ignores))
    lines = [
        f"drive_folder_id: {json.dumps(folder_id, ensure_ascii=False)}",
        f"google_native: {json.dumps(mode)}",
        f"last_sync_at: {json.dumps(last_sync) if last_sync else 'null'}",
        "ignore:",
    ]
    lines.extend(f"  - {json.dumps(item, ensure_ascii=False)}" for item in ignores)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def ignored(relative: Path, patterns: list[str], is_dir: bool) -> bool:
    rel = relative.as_posix().lstrip("./")
    for raw_pattern in patterns:
        pattern = raw_pattern.strip().replace("\\", "/")
        if not pattern:
            continue
        directory_rule = pattern.endswith("/")
        pattern = pattern.strip("/")
        if directory_rule:
            if rel == pattern or rel.startswith(pattern + "/"):
                return True
            if "/" not in pattern and pattern in relative.parts:
                return True
            continue
        if fnmatch.fnmatch(rel, pattern) or fnmatch.fnmatch(relative.name, pattern):
            return True
        if is_dir and fnmatch.fnmatch(rel + "/", pattern):
            return True
    return False


def is_generated_link(path: Path) -> bool:
    if not path.name.casefold().endswith(LINK_SUFFIX):
        return False
    try:
        return GENERATED_LINK_MARKER.encode("ascii") in path.read_bytes()[:65536]
    except OSError:
        return False


def is_generated_pointer(path: Path) -> bool:
    if path.suffix.casefold() not in set(POINTER_EXTENSIONS.values()):
        return False
    try:
        payload = json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return False
    return isinstance(payload, dict) and payload.get("") == POINTER_WARNING and bool(payload.get("doc_id"))


def stage_tree(root: Path, destination: Path, patterns: list[str]) -> tuple[int, int]:
    copied_files = 0
    ignored_entries = 0
    for current, dirs, files in os.walk(root, topdown=True, followlinks=False):
        current_path = Path(current)
        kept_dirs: list[str] = []
        for name in dirs:
            source = current_path / name
            relative = source.relative_to(root)
            if ignored(relative, patterns, True):
                ignored_entries += 1
            elif source.is_symlink():
                raise ValueError(f"symbolic link is not supported: {relative}")
            else:
                kept_dirs.append(name)
                (destination / relative).mkdir(parents=True, exist_ok=True)
        dirs[:] = kept_dirs
        for name in files:
            source = current_path / name
            relative = source.relative_to(root)
            if ignored(relative, patterns, False) or is_generated_link(source) or is_generated_pointer(source):
                ignored_entries += 1
                continue
            if source.is_symlink():
                raise ValueError(f"symbolic link is not supported: {relative}")
            target = destination / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
            copied_files += 1
    return copied_files, ignored_entries


def file_md5(path: Path) -> str:
    digest = hashlib.md5()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def drive_modified_timestamp(item: dict[str, object]) -> float | None:
    raw = str(item.get("modifiedTime") or "").strip()
    if not raw:
        return None
    try:
        parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc).timestamp()


def remote_file_index(gog: str, folder_id: str) -> dict[str, dict[str, object]]:
    result: dict[str, dict[str, object]] = {}

    def visit(remote_id: str, relative: Path) -> None:
        for item in list_drive_folder(gog, remote_id):
            name = str(item.get("name") or "")
            item_id = str(item.get("id") or "")
            mime = str(item.get("mimeType") or "")
            child = safe_child(relative, name)
            if mime == FOLDER_MIME:
                visit(item_id, child)
                continue
            key = child.as_posix().casefold()
            if key in result:
                raise ValueError(f"duplicate Drive path: {child.as_posix()}")
            result[key] = item

    visit(folder_id, Path())
    return result


def filter_staging_for_remote_newer(
    staging: Path,
    root: Path,
    remote_files: dict[str, dict[str, object]],
) -> int:
    skipped = 0
    for current, _dirs, files in os.walk(staging, topdown=True, followlinks=False):
        current_path = Path(current)
        for name in files:
            staged = current_path / name
            relative = staged.relative_to(staging)
            remote = remote_files.get(relative.as_posix().casefold())
            if remote is None:
                continue

            source = root / relative
            remote_md5 = str(remote.get("md5Checksum") or "")
            if remote_md5 and file_md5(source) == remote_md5:
                continue

            remote_mtime = drive_modified_timestamp(remote)
            local_mtime = source.stat().st_mtime
            if remote_mtime is None or remote_mtime >= local_mtime:
                staged.unlink()
                skipped += 1
                reason = "remote modifiedTime unavailable" if remote_mtime is None else "remote is newer or same age"
                print(f"skip_file\t{relative.as_posix()}\t{reason}")
    return skipped


def safe_child(parent: Path, name: str) -> Path:
    if not name or name in {".", ".."} or Path(name).name != name or "/" in name or "\\" in name:
        raise ValueError(f"unsafe Drive item name: {name!r}")
    return parent / name


def google_link_html(name: str, web_view_link: str, item_id: str) -> bytes:
    if not web_view_link:
        raise ValueError(f"Google-native file has no webViewLink: {name}")
    escaped_name = html.escape(name, quote=True)
    escaped_url = html.escape(web_view_link, quote=True)
    escaped_id = html.escape(item_id, quote=True)
    document = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  {GENERATED_LINK_MARKER}
  <meta name="gd-sync-doc-id" content="{escaped_id}">
  <meta http-equiv="refresh" content="0; url={escaped_url}">
  <title>{escaped_name}</title>
</head>
<body>
  <h1>{escaped_name}</h1>
  <p>Automatic redirection failed. <a href="{escaped_url}">Open {escaped_name}</a>.</p>
</body>
</html>
"""
    return document.encode("utf-8")


def google_pointer(item_id: str, resource_key: str, email: str) -> bytes:
    payload = {
        "": POINTER_WARNING,
        "doc_id": item_id,
        "resource_key": resource_key,
        "email": email,
    }
    return (json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n").encode("utf-8")


def auth_email(gog: str) -> str:
    completed = subprocess.run(
        [gog, "auth", "status", "--json", "--results-only"],
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    if completed.returncode != 0:
        return ""
    try:
        payload = json.loads(completed.stdout)
    except json.JSONDecodeError:
        return ""
    account = payload.get("account", {})
    return str(account.get("email") or "") if isinstance(account, dict) else ""


def list_drive_folder(gog: str, folder_id: str) -> list[dict[str, object]]:
    items: list[dict[str, object]] = []
    page = ""
    while True:
        command = [
            gog, "drive", "ls", "--parent", folder_id, "--max", "1000", "--json",
            "--fields", "files(id,name,mimeType,md5Checksum,modifiedTime,resourceKey,webViewLink),nextPageToken",
        ]
        if page:
            command.extend(["--page", page])
        completed = subprocess.run(command, check=False, capture_output=True, text=True, encoding="utf-8")
        if completed.returncode != 0:
            raise RuntimeError(completed.stderr.strip() or completed.stdout.strip() or "gog drive ls failed")
        payload = json.loads(completed.stdout)
        files = payload.get("files", [])
        if not isinstance(files, list):
            raise ValueError("unexpected gog drive ls response")
        items.extend(item for item in files if isinstance(item, dict))
        page = str(payload.get("nextPageToken") or "")
        if not page:
            return items


def pull_tree(
    gog: str,
    folder_id: str,
    root: Path,
    patterns: list[str],
    dry_run: bool,
    google_native: str,
    email: str = "",
) -> tuple[int, int, int, int]:
    creates = updates = skips = ignored_entries = 0
    seen: set[str] = set()

    def visit(remote_id: str, relative: Path) -> None:
        nonlocal creates, updates, skips, ignored_entries
        for item in list_drive_folder(gog, remote_id):
            name = str(item.get("name") or "")
            item_id = str(item.get("id") or "")
            mime = str(item.get("mimeType") or "")
            child = safe_child(relative, name)
            is_dir = mime == FOLDER_MIME
            if ignored(child, patterns, is_dir):
                ignored_entries += 1
                continue

            is_google_native = mime.startswith(GOOGLE_NATIVE_PREFIX) and not is_dir
            export_spec = GOOGLE_EXPORTS.get(mime) if google_native == "export" else None
            pointer_extension = POINTER_EXTENSIONS.get(mime) if google_native == "pointer" else None
            make_pointer = is_google_native and pointer_extension is not None
            make_link = is_google_native and export_spec is None and not make_pointer
            if make_link and not child.name.casefold().endswith(LINK_SUFFIX):
                child = child.with_name(child.name + LINK_SUFFIX)
            elif make_pointer and not child.name.casefold().endswith(pointer_extension):
                child = child.with_name(child.name + pointer_extension)
            elif export_spec and not child.name.casefold().endswith(export_spec[1]):
                child = child.with_name(child.name + export_spec[1])

            key = child.as_posix().casefold()
            if key in seen:
                raise ValueError(f"duplicate Drive path after transform: {child.as_posix()}")
            seen.add(key)
            target = root / child
            if is_dir:
                if target.exists() and not target.is_dir():
                    raise ValueError(f"remote folder conflicts with local file: {child.as_posix()}")
                if not target.exists():
                    print(f"create_folder\t{child.as_posix()}")
                    if not dry_run:
                        target.mkdir(parents=True, exist_ok=True)
                visit(item_id, child)
                continue
            if target.exists() and not target.is_file():
                raise ValueError(f"remote file conflicts with local directory: {child.as_posix()}")

            link_content = None
            pointer_content = None
            if make_link:
                link_content = google_link_html(name, str(item.get("webViewLink") or ""), item_id)
                if target.is_file() and target.read_bytes() == link_content:
                    skips += 1
                    print(f"skip_link\t{child.as_posix()}\tlink match")
                    continue
            elif make_pointer:
                pointer_content = google_pointer(
                    item_id,
                    str(item.get("resourceKey") or ""),
                    email,
                )
                if target.is_file() and target.read_bytes() == pointer_content:
                    skips += 1
                    print(f"skip_pointer\t{child.as_posix()}\tpointer match")
                    continue
            remote_md5 = str(item.get("md5Checksum") or "")
            if link_content is None and pointer_content is None and not export_spec and target.is_file() and remote_md5:
                if file_md5(target) == remote_md5:
                    skips += 1
                    print(f"skip_file\t{child.as_posix()}\tmd5 match")
                    continue

            if target.is_file():
                remote_mtime = drive_modified_timestamp(item)
                local_mtime = target.stat().st_mtime
                if remote_mtime is None or remote_mtime <= local_mtime:
                    skips += 1
                    if make_link:
                        skip_action = "skip_link"
                    elif make_pointer:
                        skip_action = "skip_pointer"
                    else:
                        skip_action = "skip_file"
                    reason = "remote modifiedTime unavailable" if remote_mtime is None else "local is newer or same age"
                    print(f"{skip_action}\t{child.as_posix()}\t{reason}")
                    continue

            if make_link:
                action = "update_link" if target.exists() else "create_link"
            elif make_pointer:
                action = "update_pointer" if target.exists() else "create_pointer"
            else:
                action = "update_file" if target.exists() else "create_file"
            if action.startswith("update"):
                updates += 1
            else:
                creates += 1
            source_kind = "webViewLink" if make_link else "Drive pointer" if make_pointer else "remote source"
            print(f"{action}\t{child.as_posix()}\t{source_kind}")
            if dry_run:
                continue

            target.parent.mkdir(parents=True, exist_ok=True)
            if link_content is not None:
                target.write_bytes(link_content)
                continue
            if pointer_content is not None:
                target.write_bytes(pointer_content)
                continue
            command = [gog, "drive", "download", item_id, "--out", str(target), "--overwrite"]
            if export_spec:
                command.extend(["--format", export_spec[0]])
            completed = subprocess.run(command, check=False)
            if completed.returncode != 0:
                raise RuntimeError(f"gog download failed: {child.as_posix()}")

    visit(folder_id, Path())
    return creates, updates, skips, ignored_entries


def setup_guidance(message: str) -> None:
    print(message, file=sys.stderr)
    print("Install: https://gogcli.sh/install.html", file=sys.stderr)
    print("Configure:", file=sys.stderr)
    print("  gog auth credentials set <oauth-client.json>", file=sys.stderr)
    print("  gog auth add <email>", file=sys.stderr)
    print("  gog auth list --check", file=sys.stderr)


def gog_failure_guidance(output: str) -> None:
    normalized = output.casefold()
    keyring_access_markers = (
        "keyring/.lock",
        "open keyring lock",
        "read-only file system",
        "permission denied",
    )
    if "keyring" in normalized and any(marker in normalized for marker in keyring_access_markers):
        print(
            "gog could not access its existing keyring in this execution environment. "
            "This does not mean the account is missing.",
            file=sys.stderr,
        )
        print(
            "Retry the same command with permission to access the user's gog keyring, "
            "then run `gog auth list --check`.",
            file=sys.stderr,
        )
        return
    if "missing --account" in normalized:
        print(
            "gog could not select an account in this execution environment. "
            "This may happen when a sandbox cannot see the existing keyring; it is not proof that no account is configured.",
            file=sys.stderr,
        )
        print(
            "Run `gog auth list --check` with permission to access the user's gog keyring, then retry.",
            file=sys.stderr,
        )
        return
    auth_markers = ("credential", "token", "unauthorized", "not authenticated")
    if any(marker in normalized for marker in auth_markers):
        print("gog authentication needs attention. Check it with:", file=sys.stderr)
        print("  gog auth list --check", file=sys.stderr)
        print("Only reconfigure credentials if that check confirms they are missing or invalid.", file=sys.stderr)


def run_pull(
    gog: str,
    folder_id: str,
    root: Path,
    patterns: list[str],
    config: dict[str, object],
    config_path: Path,
    dry_run: bool,
    update_last_sync: bool = True,
) -> int:
    try:
        creates, updates, skips, ignored_count = pull_tree(
            gog,
            folder_id,
            root,
            patterns,
            dry_run,
            str(config["google_native"]),
            auth_email(gog) if config["google_native"] == "pointer" else "",
        )
    except (OSError, RuntimeError, ValueError, json.JSONDecodeError) as exc:
        print(f"Pull failed: {exc}", file=sys.stderr)
        return 2
    print(
        f"Pull summary: create_files={creates} update_files={updates} "
        f"skip_files={skips} ignored={ignored_count}"
    )
    if dry_run:
        print("Pull dry run completed; local files and last_sync_at were not changed.")
    elif update_last_sync:
        config["last_sync_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        write_config(config_path, config)
        print(f"Pull completed; last_sync_at={config['last_sync_at']}")
    else:
        print("Pull phase completed; last_sync_at will be updated after sync.")
    return 0


def run_push(
    gog: str,
    folder_id: str,
    root: Path,
    patterns: list[str],
    config: dict[str, object],
    config_path: Path,
    dry_run: bool,
    update_last_sync: bool = True,
) -> int:
    with tempfile.TemporaryDirectory(prefix="gd-sync-") as temp_name:
        staging = Path(temp_name)
        try:
            files, skipped = stage_tree(root, staging, patterns)
            remote_files = remote_file_index(gog, folder_id)
            skipped_remote = filter_staging_for_remote_newer(staging, root, remote_files)
        except (OSError, ValueError) as exc:
            print(f"Could not prepare synchronization: {exc}", file=sys.stderr)
            return 2
        print(
            f"Prepared {files} file(s); ignored {skipped} entry/entries; "
            f"skipped {skipped_remote} remote-newer file(s)."
        )
        command = [gog, "drive", "sync", "push", str(staging), "--parent", folder_id]
        if dry_run:
            command.append("--dry-run")
        completed = subprocess.run(command, check=False, capture_output=True, text=True, encoding="utf-8")

    if completed.stdout:
        print(completed.stdout, end="" if completed.stdout.endswith("\n") else "\n")
    if completed.stderr:
        print(completed.stderr, end="" if completed.stderr.endswith("\n") else "\n", file=sys.stderr)

    if completed.returncode != 0:
        print("gog push failed.", file=sys.stderr)
        gog_failure_guidance("\n".join((completed.stdout, completed.stderr)))
        return completed.returncode
    if dry_run:
        print("Dry run completed; last_sync_at was not changed.")
    elif update_last_sync:
        config["last_sync_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        write_config(config_path, config)
        print(f"Push completed; last_sync_at={config['last_sync_at']}")
    else:
        print("Push phase completed; last_sync_at will be updated after sync.")
    return 0


def run_sync(
    gog: str,
    folder_id: str,
    root: Path,
    patterns: list[str],
    config: dict[str, object],
    config_path: Path,
    dry_run: bool,
) -> int:
    print("Sync compares local and remote modified times: newer local files are pushed; newer remote files are pulled.")
    result = run_pull(gog, folder_id, root, patterns, config, config_path, dry_run, update_last_sync=False)
    if result != 0:
        return result
    result = run_push(
        gog,
        folder_id,
        root,
        patterns,
        config,
        config_path,
        dry_run,
        update_last_sync=False,
    )
    if result == 0 and not dry_run:
        config["last_sync_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        write_config(config_path, config)
        print(f"Sync completed; last_sync_at={config['last_sync_at']}")
    return result


def main() -> int:
    configure_stdio()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="local directory containing gd-sync.yml")
    parser.add_argument(
        "--direction",
        choices=("sync", "push", "pull"),
        default="sync",
        help="sync both ways by modification time, or force one direction",
    )
    parser.add_argument("--dry-run", action="store_true", help="show gog's reconciliation plan")
    args = parser.parse_args()
    root = Path(args.root).expanduser().resolve()
    if not root.is_dir():
        print(f"Local root is not a directory: {root}", file=sys.stderr)
        return 2

    gog = find_gog()
    if not gog:
        setup_guidance("gog CLI was not found on PATH or in ~/.local/bin.")
        return 3
    if subprocess.run([gog, "--version"], check=False).returncode != 0:
        setup_guidance("gog CLI exists but could not run.")
        return 3
    auth_status = subprocess.run(
        [gog, "auth", "status"], check=False, capture_output=True, text=True, encoding="utf-8"
    )
    if auth_status.returncode != 0:
        auth_output = "\n".join(part for part in (auth_status.stdout, auth_status.stderr) if part).strip()
        if auth_output:
            print(auth_output, file=sys.stderr)
        gog_failure_guidance(auth_output)
        return 4

    config_path = root / CONFIG_NAME
    if not config_path.exists():
        write_config(config_path, {
            "drive_folder_id": "REPLACE_WITH_DRIVE_FOLDER_ID",
            "google_native": "html",
            "last_sync_at": "",
            "ignore": DEFAULT_IGNORES,
        })
        print(f"Created configuration: {config_path}")
        print("Set drive_folder_id, then run the command again.")
        return 2
    try:
        config = load_config(config_path)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"Invalid {CONFIG_NAME}: {exc}", file=sys.stderr)
        return 2

    folder_id = str(config["drive_folder_id"]).strip()
    if not folder_id or folder_id == "REPLACE_WITH_DRIVE_FOLDER_ID":
        print(f"Set drive_folder_id in {config_path}", file=sys.stderr)
        return 2

    patterns = [str(item) for item in config["ignore"]]
    if args.direction == "pull":
        return run_pull(gog, folder_id, root, patterns, config, config_path, args.dry_run)
    if args.direction == "push":
        return run_push(gog, folder_id, root, patterns, config, config_path, args.dry_run)

    return run_sync(gog, folder_id, root, patterns, config, config_path, args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
